services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    volumes:
      - ./src:/app/src
      - ./uploads:/tmp/uploads
      - ./gw2ei.conf:/app/GW2EIParser/gw2ei.conf
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./nodemon.json:/app/nodemon.json
    ports:
      - "3000:3000"
    command: ["npx", "nodemon"]

  cli-builder:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
